language: python
cache: false
sudo: true
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - sudo apt-get update
  # Extra dependencies for testing and coverage
  - sudo pip3 install pytest
  - sudo pip3 install coveralls
  - sudo pip3 install coverage
  # Fix required to get Cython working
  - sudo pip3 install --upgrade cython
  - sudo python3 setup.py install

script:
  - coverage run --source cubature -m py.test
  - coverage report

after_success:
  - coveralls

notifications:
  email:
    on_success: change
    on_failure: change
