language: python
cache: false
sudo: false
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - sudo apt-get update
  # Extra dependencies for testing and coverage
  - pip install pytest
  - pip install coveralls
  - pip install coverage
  # Fix required to get Cython working
  - pip install --upgrade cython
  - python setup.py build_ext --inplace
  - python setup.py install

script:
  - coverage run --source cubature -m py.test
  - coverage report

after_success:
  - coveralls

notifications:
  email:
    on_success: change
    on_failure: change
